version: '3.9'

services:
    app:
        build: .
        container_name: weather-app
        ports:
            - '${APP_PORT}:3000'
        env_file:
            - .env
        depends_on:
            - postgres
        command: sh -c "npx prisma migrate deploy && node dist/src/main"

    postgres:
        image: postgres:16
        container_name: postgres
        restart: always
        ports:
            - '${DB_PORT}:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
